export default [
  { name: 'BTC-USD', value: 'btcusd' },
  { name: 'BTC-EUR', value: 'btceur' },
  { name: 'EUR-USD', value: 'eurusd' },
  { name: 'XRP-USD', value: 'xrpusd' },
  { name: 'XRP-EUR', value: 'xrpeur' },
  { name: 'XRP-BTC', value: 'xrpbtc' },
  { name: 'LTC-USD', value: 'ltcusd' },
  { name: 'LTC-EUR', value: 'ltceur' },
  { name: 'LTC-BTC', value: 'ltcbtc' },
  { name: 'ETH-USD', value: 'ethusd' },
  { name: 'ETH-EUR', value: 'etheur' },
  { name: 'ETH-BTC', value: 'ethbtc' },
  { name: 'BCH-USD', value: 'bchusd' },
  { name: 'BCH-EUR', value: 'bcheur' },
  { name: 'BCH-BTC', value: 'bchbtc' },
];
